---
- name: Determine installed ssr version
  command: simplescreenrecorder --version
  register: ssr_installed_version
  changed_when: false
  failed_when: false

- name: Install prerequisites
  apt:
    pkg:
      - build-essential
      - cmake
      - pkg-config
      - desktop-file-utils
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - qt5-qmake
      - qttools5-dev
      - qtbase5-dev
      - libqt5x11extras5-dev
      - libavformat-dev
      - libavcodec-dev
      - libavutil-dev
      - libswscale-dev
      - libasound2-dev
      - libpulse-dev
      - libjack-dev
      - libx11-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxinerama-dev
      - libv4l-dev

# https://github.com/jdauphant/ansible-role-packaging/blob/master/tasks/Debian.yml
- name: Check if i386 is enabled
  shell: >
    set -o pipefail && \
      dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  args:
    executable: /bin/bash
- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1
- name: Ensure apt cache is up to date
  apt: update_cache=yes
  when: result_i386_check.rc == 1

- name: Install 32bit prerequisites
  apt:
    pkg:
      - g++-multilib
      - libgl1-mesa-dev:i386
      - libglu1-mesa-dev:i386
      - libx11-dev:i386
      - libxfixes-dev:i386

- block:
    - name: Clone ssr repository
      git:
        repo: https://github.com/MaartenBaert/ssr
        version: master
        dest: "{{ ssr_installdir }}"

    - name: Allow non-root to install ssr
      file:
        path: "{{ ssr_installdir }}"
        state: directory
        mode: 0777

    - name: Install ssr
      command:
        cmd: ./simple-build-and-install
        chdir: "{{ ssr_installdir }}"
      become: false
      when: ssr_ci is not defined
  when: >
    ssr_installed_version.stderr is not defined
    or ssr_version not in ssr_installed_version.stderr
